In [5]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
Y = iris.target
N_NEIGHBORS = 3

In [6]:
number_of_vectors, vector_length = X.shape

In [7]:
!pip install annoy
# !pip install git+git://github.com/spotify/annoy.git

You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [8]:
# https://github.com/spotify/annoy
from annoy import AnnoyIndex
import numpy as np


ann_index = AnnoyIndex(vector_length, metric='euclidean') 
for i in range(number_of_vectors):
    vector = X[i,:]
    ann_index.add_item(i, vector)

ann_index.build(10) # 10 trees, larger value will give more accurate results, but larger indexes

# find 2 nearest neighbours for every vector from X
annoy_indices = np.array([ann_index.get_nns_by_vector(vector, N_NEIGHBORS) for vector in X])
annoy_indices

array([[  0,  17,   4],
       [  1,  12,  45],
       [  2,  47,   3],
       [  3,  47,  29],
       [  4,   0,  17],
       [  5,  18,  10],
       [  6,  47,   2],
       [  7,  39,  49],
       [  8,  38,   3],
       [  9,  34,  37],
       [ 10,  48,  36],
       [ 11,   7,  29],
       [ 12,   1,   9],
       [ 13,  38,  42],
       [ 14,  33,  16],
       [ 15,  33,  14],
       [ 16,  10,  33],
       [ 17,   0,  40],
       [ 18,   5,  10],
       [ 19,  21,  46],
       [ 20,  31,  27],
       [ 21,  19,  46],
       [ 22,   6,   2],
       [ 23,  26,  43],
       [ 24,  11,  29],
       [ 25,   9,  34],
       [ 26,  23,  43],
       [ 27,  39,   0],
       [ 28,   0,  27],
       [ 29,  30,   3],
       [ 30,  29,   9],
       [ 31,  20,  27],
       [ 32,  46,  33],
       [ 33,  32,  15],
       [  9,  34,  37],
       [ 35,  49,   1],
       [ 36,  10,  31],
       [  9,  34,  37],
       [ 38,   8,  42],
       [ 39,   7,  27],
       [ 40,  17,   0],
       [ 41,   8

In [18]:
!pip install git+git://github.com/facebookresearch/pysparnn.git

  Cloning git://github.com/facebookresearch/pysparnn.git to /tmp/pip-6QKFyw-build
  Running setup.py install for pysparnn ... - done
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [ ]:
!pip 

In [24]:
# https://github.com/facebookresearch/pysparnn
import pysparnn.cluster_index as ci
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=.2)

cp = ci.MultiClusterIndex(X_train, y_train)

list(zip(cp.search(X_test, k=1, return_distance=False), y_test))

ImportError: No module named 'pysparnn'

In [12]:
# http://scikit-learn.org/0.18/modules/generated/sklearn.neighbors.LSHForest.html#sklearn.neighbors.LSHForest
from sklearn.neighbors import LSHForest

lshf = LSHForest(random_state=42)
lshf.fit(X, Y) 
lshf_distances, lshf_indices = lshf.kneighbors(X, n_neighbors=N_NEIGHBORS)
lshf_indices                                      

/home/tkopec/.local/lib/python3.5/site-packages/sklearn/neighbors/approximate.py:220: DeprecationWarning: LSHForest has poor performance and has been deprecated in 0.19. It will be removed in version 0.21.
  DeprecationWarning)
/home/tkopec/.local/lib/python3.5/site-packages/sklearn/random_projection.py:378: DataDimensionalityWarning: The number of components is higher than the number of features: n_features < n_components (4 < 32).The dimensionality of the problem will not be reduced.
  DataDimensionalityWarning)


array([[  0,  10,   2],
       [  1,  12,  45],
       [  2,   0,  10],
       [  3,   8,  29],
       [  4,  42,  48],
       [  5,   6,  21],
       [  6,  19,  21],
       [  7,  38,  39],
       [  8,   3,  30],
       [ 34,  37,   9],
       [ 10,   0,   2],
       [ 11,  29,  47],
       [ 12,  37,   9],
       [ 13,   0,  10],
       [ 14,  13,  16],
       [ 15,  33,  19],
       [ 16,  40,  15],
       [ 17,   2,  40],
       [ 18,  39,  38],
       [ 19,   6,  42],
       [ 20,  34,  37],
       [ 21,   6,   5],
       [ 22,  33,  15],
       [ 23,  26,  43],
       [ 24,  29,  44],
       [ 25,  20,   1],
       [ 26,  18,   5],
       [ 27,  39,  38],
       [ 28,  49,  27],
       [ 29,   3,  11],
       [ 30,   8,  20],
       [ 31,  45,   1],
       [ 32,  33,  46],
       [ 33,  15,  32],
       [ 34,  37,   9],
       [ 35,  36,  28],
       [ 36,  35,  28],
       [ 34,  37,   9],
       [ 38,   7,  27],
       [ 39,  27,   7],
       [ 40,  17,   0],
       [ 41,  25

In [13]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=N_NEIGHBORS)
classifier.fit(X, Y)
distances, indices = classifier.kneighbors(X)
indices

array([[  0,  17,   4],
       [  1,  45,  12],
       [  2,  47,   3],
       [  3,  47,  29],
       [  4,   0,  17],
       [  5,  18,  10],
       [  6,  47,   2],
       [  7,  39,  49],
       [  8,  38,   3],
       [  9,  34,  37],
       [ 10,  48,  27],
       [ 11,  29,   7],
       [ 12,   1,  34],
       [ 13,  38,  42],
       [ 14,  33,  16],
       [ 15,  33,  14],
       [ 16,  10,  48],
       [ 17,   0,  40],
       [ 18,   5,  10],
       [ 19,  21,  46],
       [ 20,  31,  27],
       [ 21,  19,  46],
       [ 22,   6,   2],
       [ 23,  26,  43],
       [ 24,  11,  29],
       [ 25,  37,  34],
       [ 26,  23,  43],
       [ 27,  28,   0],
       [ 28,  27,   0],
       [ 29,  30,   3],
       [ 30,  29,  34],
       [ 31,  20,  27],
       [ 32,  46,  33],
       [ 33,  32,  15],
       [  9,  34,  37],
       [ 35,  49,   1],
       [ 36,  10,  31],
       [  9,  34,  37],
       [ 38,   8,  42],
       [ 39,   7,   0],
       [ 40,  17,   0],
       [ 41,   8

In [14]:
import pandas as pd

In [15]:
d = {'KNeighborsClassifier': list(indices), 'annoy': list(annoy_indices), 'lshforest': list(lshf_indices)}
df = pd.DataFrame(d, index=range(number_of_vectors))

pd.set_option('display.max_rows', number_of_vectors)
df

KNeighborsClassifier            annoy        lshforest
0             [0, 17, 4]       [0, 17, 4]       [0, 10, 2]
1            [1, 45, 12]      [1, 12, 45]      [1, 12, 45]
2             [2, 47, 3]       [2, 47, 3]       [2, 0, 10]
3            [3, 47, 29]      [3, 47, 29]       [3, 8, 29]
4             [4, 0, 17]       [4, 0, 17]      [4, 42, 48]
5            [5, 18, 10]      [5, 18, 10]       [5, 6, 21]
6             [6, 47, 2]       [6, 47, 2]      [6, 19, 21]
7            [7, 39, 49]      [7, 39, 49]      [7, 38, 39]
8             [8, 38, 3]       [8, 38, 3]       [8, 3, 30]
9            [9, 34, 37]      [9, 34, 37]      [34, 37, 9]
10          [10, 48, 27]     [10, 48, 36]       [10, 0, 2]
11           [11, 29, 7]      [11, 7, 29]     [11, 29, 47]
12           [12, 1, 34]       [12, 1, 9]      [12, 37, 9]
13          [13, 38, 42]     [13, 38, 42]      [13, 0, 10]
14          [14, 33, 16]     [14, 33, 16]     [14, 13, 16]
15          [15, 33, 14]     [15, 33, 14]     [15, 33, 19]
16          [16, 10, 48]     [16, 10, 33]     [16, 40, 15]
17           [17, 0, 40]      [17, 0, 40]      [17, 2, 40]
18           [18, 5, 10]      [18, 5, 10]     [18, 39, 38]
19          [19, 21, 46]     [19, 21, 46]      [19, 6, 42]
20          [20, 31, 27]     [20, 31, 27]     [20, 34, 37]
21          [21, 19, 46]     [21, 19, 46]       [21, 6, 5]
22            [22, 6, 2]       [22, 6, 2]     [22, 33, 15]
23          [23, 26, 43]     [23, 26, 43]     [23, 26, 43]
24          [24, 11, 29]     [24, 11, 29]     [24, 29, 44]
25          [25, 37, 34]      [25, 9, 34]      [25, 20, 1]
26          [26, 23, 43]     [26, 23, 43]      [26, 18, 5]
27           [27, 28, 0]      [27, 39, 0]     [27, 39, 38]
28           [28, 27, 0]      [28, 0, 27]     [28, 49, 27]
29           [29, 30, 3]      [29, 30, 3]      [29, 3, 11]
30          [30, 29, 34]      [30, 29, 9]      [30, 8, 20]
31          [31, 20, 27]     [31, 20, 27]      [31, 45, 1]
32          [32, 46, 33]     [32, 46, 33]     [32, 33, 46]
33          [33, 32, 15]     [33, 32, 15]     [33, 15, 32]
34           [9, 34, 37]      [9, 34, 37]      [34, 37, 9]
35           [35, 49, 1]      [35, 49, 1]     [35, 36, 28]
36          [36, 10, 31]     [36, 10, 31]     [36, 35, 28]
37           [9, 34, 37]      [9, 34, 37]      [34, 37, 9]
38           [38, 8, 42]      [38, 8, 42]      [38, 7, 27]
39            [39, 7, 0]      [39, 7, 27]      [39, 27, 7]
40           [40, 17, 0]      [40, 17, 0]      [40, 17, 0]
41           [41, 8, 38]      [41, 8, 38]      [41, 25, 1]
42          [42, 38, 47]     [42, 38, 47]      [42, 4, 19]
43          [43, 26, 23]     [43, 26, 23]      [43, 26, 5]
44           [44, 46, 5]      [44, 46, 5]      [44, 24, 5]
45           [45, 1, 12]      [45, 1, 12]      [45, 31, 1]
46          [46, 19, 21]     [46, 19, 21]     [46, 42, 19]
47            [47, 3, 2]       [47, 2, 3]      [47, 7, 38]
48          [48, 10, 27]     [48, 10, 27]      [48, 10, 0]
49           [49, 7, 39]      [49, 7, 39]     [49, 28, 27]
50          [50, 52, 86]     [50, 52, 86]     [50, 74, 82]
51          [51, 56, 75]     [51, 56, 75]     [51, 99, 61]
52          [52, 50, 86]     [52, 50, 86]     [52, 86, 92]
53          [53, 89, 80]     [53, 89, 80]     [53, 54, 77]
54          [54, 58, 75]     [54, 58, 75]     [54, 52, 53]
55          [55, 66, 90]     [55, 66, 90]     [55, 63, 90]
56          [56, 51, 85]     [56, 51, 85]     [56, 59, 96]
57          [57, 93, 98]     [57, 93, 98]     [57, 82, 65]
58          [58, 75, 54]     [58, 75, 54]     [58, 80, 69]
59          [59, 89, 94]     [59, 89, 53]     [59, 56, 61]
60          [60, 93, 57]     [60, 93, 57]     [60, 76, 87]
61          [61, 96, 78]     [61, 96, 95]     [61, 51, 56]
62          [62, 92, 69]     [62, 92, 69]     [62, 87, 60]
63          [63, 91, 73]     [63, 91, 73]     [63, 55, 94]
64          [64, 82, 79]     [64, 82, 79]     [64, 57, 98]
65          [65, 75, 58]     [65, 75, 58]     [65, 71, 93]
66          [66, 84, 55]     [66, 84, 55]     [66, 